### PR TITLE
Delete webpack.config.js

### PR DESCRIPTION
**Pull request by harvli**
Co-authored-by: Harvey Li <112590580+harvli@users.noreply.github.com>
Co-authored-by: John Wroge <72668920+johnwroge@users.noreply.github.com>
Co-authored-by: Aimée Nguyen <106037255+DoctorCodeine@users.noreply.github.com>
Co-authored-by: Ed Cho <106274379+edcho720@users.noreply.github.com>

### CODE REVIEW

**Review by johnwroge — APPROVED** [review]
Deleted.

**Review by edcho720 — APPROVED** [review]
Looks good

**Review by edcho720 — COMMENTED** [review]
Good job

**Review by edcho720 — COMMENTED** [review]
Great

**Review by edcho720 — COMMENTED** [review]
Super

**Pull request merged**
